"""Display Protocol shared by hardware and mock implementations."""
from __future__ import annotations
from typing import Protocol
from PIL import Image


class Display(Protocol):
    width: int
    height: int

    def display_full(self, img: Image.Image) -> None: ...
    def enter_partial_mode(self) -> None: ...
    def display_partial(self, img: Image.Image) -> None: ...
    def exit_partial_mode(self) -> None: ...
    def deep_clean(self) -> None: ...
    def shutdown(self, farewell: Image.Image | None = None) -> None: ...
